#!/bin/bash

# choose image tag
TAG=`git symbolic-ref --short HEAD`
if [ "$TAG" = "master" ]; then
    TAG=latest
fi

if [ -w /var/run/docker.sock ]; then
    exec docker build "$@" --tag leprikon/leprikon:$TAG .
else
    exec sudo docker build "$@" --tag leprikon/leprikon:$TAG .
fi
